In [7]:
import jax.numpy as jnp
from flax import nnx
import jax.random as jrandom

In [6]:
rngs = nnx.Rngs(1)

In [39]:
N = 6
D = jrandom.uniform(rngs.params(), (N,))
L = jrandom.uniform(rngs.params(), (N,))[:, None]
R = jrandom.uniform(rngs.params(), (N,))[:, None]
D, L, R

(Array([0.21141422, 0.26532292, 0.48673534, 0.93313956, 0.31153643,
        0.27658606], dtype=float32),
 Array([[0.17975795],
        [0.6841978 ],
        [0.8187438 ],
        [0.16968453],
        [0.97645533],
        [0.22552824]], dtype=float32),
 Array([[0.8320503 ],
        [0.01563358],
        [0.25278413],
        [0.4280287 ],
        [0.9957123 ],
        [0.64372504]], dtype=float32))

In [63]:
jnp.exp(L @ R.T)

Array([[1.161332 , 1.0028143, 1.0464882, 1.079979 , 1.1960055, 1.1226755],
       [1.7670068, 1.0107539, 1.1888119, 1.3402501, 1.9763746, 1.5533831],
       [1.9763191, 1.0128821, 1.22994  , 1.4197004, 2.2597027, 1.6939209],
       [1.1516389, 1.0026563, 1.0438268, 1.0753325, 1.1840692, 1.115419 ],
       [2.2534447, 1.0153826, 1.2799647, 1.518846 , 2.643936 , 1.8749253],
       [1.2064122, 1.003532 , 1.0586663, 1.1013454, 1.2517734, 1.1562456]],      dtype=float32)

In [61]:
trace = jnp.sum(L * R)
trace

Array(1.557306, dtype=float32)

In [65]:
print(jnp.eye(N) + (jnp.e ** trace - 1)/trace * L @ R.T)

[[1.3597772  0.00675994 0.10930344 0.1850789  0.43054435 0.27834564]
 [1.3693901  1.0257298  0.41603264 0.7044505  1.6387453  1.059444  ]
 [1.6386777  0.03078949 1.4978446  0.8429792  1.961001   1.2677814 ]
 [0.3396157  0.00638112 0.10317821 1.1747073  0.40641716 0.2627475 ]
 [1.9543301  0.03672035 0.5937425  1.005359   3.3387413  1.5119894 ]
 [0.4513843  0.00848116 0.13713448 0.23220402 0.5401703  1.3492185 ]]
